default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: asdpoi04
  host: localhost
  pool: 5

development:
  <<: *default
  database: consulta_cpf_development

test:
  <<: *default
  database: consulta_cpf_test

production:
  <<: *default
  database: consulta_cpf_production
  username: consulta_cpf
  password: <%= ENV["CONSULTA_CPF_DATABASE_PASSWORD"] %>
